#!/usr/bin/env python

import sys
cmd=0
var="x"
level=0
while True:
	cmd=cmd+1
	var=sys.stdin.read(1)
	if level == 0:
		if var == "+":
			level=level+1
			if level<0:
				print cmd
			else:
				continue
		elif var == "-":
			level=level-1
			if level<0:
				print cmd
			else:
				continue
		else:
			break
	else:
		if var == "+":
			level=level+1
		elif var == "-":
			level=level-1
		else:
			break
